use crate::bindings::SelectedArtifactBinding;
use crate::models::VerificationStatus;
use anyhow::Result;
use std::path::Path;

pub fn render_binding_report(bindings: &[SelectedArtifactBinding]) -> String {
    // Dedup bindings by canonical_id, keeping first occurrence
    let mut seen = std::collections::BTreeSet::new();
    let bindings: Vec<_> = bindings.iter().filter(|b| seen.insert(b.canonical_id.clone())).collect();
    let bindings = bindings.as_slice();
    let total = bindings.len();
    let verified = bindings.iter().filter(|b| b.verification_status == VerificationStatus::Verified).count();
    let unverified = total - verified;

    let rows: String = bindings.iter().map(|b| {
        let (status_class, status_label) = match &b.verification_status {
            VerificationStatus::Verified => ("verified", "VERIFIED"),
            VerificationStatus::Unverified { reason } => ("unverified", match reason {
                crate::models::UnverifiedReason::NotFound => "UNVERIFIED — NOT FOUND",
                crate::models::UnverifiedReason::AmbiguousMatch => "UNVERIFIED — AMBIGUOUS",
                crate::models::UnverifiedReason::ApiError => "UNVERIFIED — API ERROR",
                crate::models::UnverifiedReason::DigestMismatch => "UNVERIFIED — DIGEST MISMATCH",
            }),
        };

        let url_cell = match &b.absolute_url {
            Some(url) => format!("<a href=\"https://www.courtlistener.com{}\">View</a>", url),
            None => "—".to_string(),
        };

        format!(
            "<tr class=\"{}\"><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td><code>{}</code></td><td>{}</td></tr>\n",
            status_class,
            status_label,
            escape_html(&b.case_name),
            escape_html(&b.citations.join(", ")),
            b.date_filed.clone().unwrap_or_else(|| "—".to_string()),
            b.canonical_id,
            url_cell,
        )
    }).collect();

    format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>CiteRight Verification Report</title>
<style>
  body {{ font-family: Georgia, serif; max-width: 1100px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }}
  h1 {{ font-size: 1.6em; border-bottom: 2px solid #1a1a1a; padding-bottom: 8px; }}
  .summary {{ background: #f5f5f5; border-left: 4px solid #333; padding: 16px 20px; margin: 24px 0; }}
  .summary h2 {{ margin: 0 0 8px 0; font-size: 1em; text-transform: uppercase; letter-spacing: 0.05em; }}
  .count {{ display: inline-block; margin-right: 32px; font-size: 1.4em; font-weight: bold; }}
  .count span {{ display: block; font-size: 0.55em; font-weight: normal; text-transform: uppercase; letter-spacing: 0.08em; color: #555; }}
  .verified-count {{ color: #1a6b1a; }}
  .unverified-count {{ color: #b30000; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 24px; font-size: 0.92em; }}
  th {{ background: #1a1a1a; color: white; padding: 10px 12px; text-align: left; font-weight: normal; text-transform: uppercase; letter-spacing: 0.05em; font-size: 0.85em; }}
  td {{ padding: 10px 12px; border-bottom: 1px solid #ddd; vertical-align: top; }}
  tr.verified td:first-child {{ color: #1a6b1a; font-weight: bold; }}
  tr.unverified {{ background: #fff5f5; }}
  tr.unverified td:first-child {{ color: #b30000; font-weight: bold; }}
  code {{ font-size: 0.82em; background: #f0f0f0; padding: 2px 4px; border-radius: 2px; }}
  .footer {{ margin-top: 40px; font-size: 0.8em; color: #888; border-top: 1px solid #ddd; padding-top: 16px; }}
</style>
</head>
<body>
<h1>CiteRight Citation Verification Report</h1>
<div class="summary">
  <h2>Verification Summary</h2>
  <div class="count verified-count">{verified}<span>Verified</span></div>
  <div class="count unverified-count">{unverified}<span>Unverified</span></div>
  <div class="count">{total}<span>Total Citations</span></div>
</div>
<table>
<thead>
<tr><th>Status</th><th>Case Name</th><th>Citation(s)</th><th>Date Filed</th><th>Canonical ID</th><th>Source</th></tr>
</thead>
<tbody>
{rows}
</tbody>
</table>
<div class="footer">Generated by CiteRight &mdash; deterministic citation verification pipeline</div>
</body>
</html>"#,
        verified = verified,
        unverified = unverified,
        total = total,
        rows = rows,
    )
}

pub fn write_binding_report(path: &Path, bindings: &[SelectedArtifactBinding]) -> Result<()> {
    let report = render_binding_report(bindings);
    std::fs::write(path, report)?;
    Ok(())
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
     .replace('<', "&lt;")
     .replace('>', "&gt;")
     .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_empty_report() {
        let report = render_binding_report(&[]);
        assert!(report.contains("CiteRight Citation Verification Report"));
        assert!(report.contains("Verified Summary") || report.contains("Verification Summary"));
    }
}
